### ISSUE TITLE
ヒストグラムがスカスカになる

### ISSUE THREAD

**Issue by matsudo840** [RTstudy/StatisticsStudy#1]
[https://github.com/RTstudy/StatisticsStudy/blob/master/exercise_01/exercise_01_matsudo840.ipynb](url)
```
from scipy.stats import norm
ax = sns.distplot(Z, kde=False, rug=False, fit=norm, bins=11)
```
`bins=11`を省略すると、ヒストグラムの棒の間にスペースができてしまう。
きれいに書く方法はないか？

**Comment by wankoSato** [comment]
`sns.countplot`で棒グラフにできます。色のオプションなしだと虹色になってしまいますがｗ

```
import pandas as pd
Z_df = pd.DataFrame({"num":Z})
ax = sns.countplot(x="num",data=Z_df)
```

ヒストグラムはもともと連続変数を特定区間で区切ったときのカウントを示すものなので、今回のような離散値のカウントをする場合はbinsを指定しないと、区間幅が存在しないのでスカスカになってしまいます。

さいころの目はカテゴリ変数と同じ扱いなので、グラフの持つ意味としてはヒストグラムではなく棒グラフの方が正しいです。
