### ISSUE TITLE
Jupyter notebookでスライダーが表示されない

### ISSUE THREAD

**Issue by matsudo840** [RTstudy/StatisticsStudy#2]
```
def f(myu, sigma):
  Z = (X-myu)/sigma
  meanZ = np.mean(Z)
  varZ = np.var(Z)
  print('mean={}, var={}'.format(meanZ, varZ))

  plt.xlim(-10, 10)  
  plt.hist(Z)
  plt.show;
  return

interact(f, myu=(-7.0,7.0,0.1), sigma=(0.0,2.0,0.1));
```

コードを実行しても、スライダーが表示されない。
Google colabなら表示される。

**Comment by wankoSato** [comment]
動きましたー

いろいろいじってたらいつの間にか動いた感じなのでどこが原因だったのか切り分けできてないんですが、おそらく

- nodejsのインストールが必要
- 機能拡張を有効にしないとダメ

辺りかな、と思っています。
ちなみに自分の環境は

- Windows10
- Anaconda
- JupyterLab(Chrome上で動作)

です。

参考：
[Installation](https://ipywidgets.readthedocs.io/en/latest/user_install.html)
[Anaconda Navigator でサクッと jupyter nbextensions を入れる](https://qiita.com/Surpris/items/7e5770b42ee666ca52e6)
[AnacondaのJupyter notebookでnbextensionsを使う](https://qiita.com/SaitoTsutomu/items/1326e05eb992a8aa849d)
[JupyterLabのおすすめ拡張機能8選](https://qiita.com/canonrock16/items/d166c93087a4aafd2db4)

![キャプチャ](https://user-images.githubusercontent.com/30205993/77818060-e2676b80-7112-11ea-96c1-490ea2013415.PNG)

**Comment by matsudo840** [comment]
どの環境でも動作するコードではなかったですね…。
ともあれ、動いてよかったです。
