### ISSUE TITLE
実践問題3 extra

### ISSUE THREAD

**Issue by matsudo840** [RTstudy/StatisticsStudy#3]
@wankoSato からのリクエスト
-----
自分でやろうと思っていたのですが、ちょっと時間なさそうなのでもし時間あれば実践問題の方のextraで以下のこともやってみてもらっても良いですか？

> 1.実践問題の初期設定で、X^2のときの期待値と分散を求めよ。また、数値シミュレーションした際の分布を描け。
> 2.XをZに変換したときのZ^2の期待値と分散を求めよ。また、数値シミュレーションした際の分布を描け。
> 3.それぞれ独立に標準正規分布に従う確率変数X_1,X_2,X_3, ... ,X_iがあるとき、i=1,2,3のときのそれぞれのΣX_i^2 の期待値と分散を求めよ。また、数値シミュレーションした際の分布を描け。

足し算引き算だけだと簡単なのと、特に3.はそのままχ二乗分布の定義になっているので、ついでにここで扱っても良いとおもいました。自分のマセマ本では125ページから説明があります。
かなり面倒な説明になっています。が、MITの数理統計のコースでは上記のような説明ですごく分かりやすかったので、ここにいれておきました。
お時間あれば、jupyterで数式も書いていただけるとうれしいです。

**Comment by wankoSato** [comment]
数式による解法を追加しました。
これでやると、標準正規分布に従うXのX^2における期待値と分散が以下のようになります。

E[X^2] = 1
V(X^2) = 2

この値は数値シミュレーションしていただいた結果と合致します。
この値を求める過程でE[X^4]の値が必要になってきますが、その値は標準正規分布のモーメント母関数から求めることができます。マセマ本p34からあるように、確率変数Xのn乗の期待値はモーメント母関数M(θ)をn階微分したものにθ=0を代入すると求めることができます。

その一連の過程を示しましたので、ご確認ください。
ちなみに、正規分布のモーメント母関数はマセマ本p96にあり、μ=0、σ=1とすれば標準席分布のモーメント母関数になります。

ちなみに[integral calculator](https://www.integral-calculator.com/)で

x^4*1/(sqrt(2pi))*exp(-x^2/2)

を-∞~+∞で積分してE[X^4]を求めた場合でも値が3になったので、たぶん計算はあっているはずです。

**Comment by matsudo840** [comment]
完全に理解しました。
